spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      properties:
        format_sql: true
      database: postgres
      database-platform: org.hibernate.dialect.PostgreSQLDialect

      transaction:
        jta:
          platform:

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 604800000

  payment:
    stripe:
      secret-key: ${STRIPE_SECRET_KEY}
      endpoint-secret: ${STRIPE_ENDPOINT_SECRET}

  frontend:
    url: ${FRONTEND_URL}
    social-signin-redirect-url: ${SOCIAL_SIGNIN_REDIRECT_URL}
